In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies=movies.merge(credits,on="title")

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movies=movies[["id","title","genres","keywords","overview","cast","crew"]]

In [8]:
movies.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

id          0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4806 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4806 non-null   int64
 1   title     4806 non-null   object
 2   genres    4806 non-null   object
 3   keywords  4806 non-null   object
 4   overview  4806 non-null   object
 5   cast      4806 non-null   object
 6   crew      4806 non-null   object
dtypes: int64(1), object(6)
memory usage: 187.7+ KB

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[0]

id                                                      19995
title                                                  Avatar
genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
overview    In the 22nd century, a paraplegic Marine is di...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

https://www.geeksforgeeks.org/python-convert-a-string-representation-of-list-into-list/

In [15]:
import ast
def genre_list(list_dict):
    lis=[]
    for dic in ast.literal_eval(list_dict):
        lis.append(dic["name"])
    return lis

In [16]:
genre_list(movies.iloc[0].genres)

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [17]:
movies['genres']=movies['genres'].apply(genre_list)
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [18]:
movies.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['keywords']=movies['keywords'].apply(genre_list)
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [20]:
movies.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [22]:
import ast
def convert2(list_dict):
    cnt=0
    lis=[]
    for dic in ast.literal_eval(list_dict):
        if cnt!=5:
            lis.append(dic["name"])
        else:
            break
        cnt+=1
    return lis

In [23]:
movies['cast']=movies['cast'].apply(convert2)
movies['cast']

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4806, dtype: object

In [24]:
movies['cast'][0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez']

In [25]:
movies.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
def convert3(list_dict):
    import ast
    direct=[]
    for dic in ast.literal_eval(list_dict):
        if dic['job']=="Director":
            direct.append(dic["name"])
            break
    return direct

In [27]:
convert3(movies['crew'][0])

['James Cameron']

In [28]:
movies["crew"]=movies["crew"].apply(convert3)
movies["crew"]

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [29]:
movies.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [30]:
movies["overview"]

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: overview, Length: 4806, dtype: object

In [31]:
movies["overview"]

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: overview, Length: 4806, dtype: object

In [32]:
def convert_overview(overview):
    from nltk.corpus import stopwords
    from nltk.tokenize import word_tokenize
    stop_words = set(stopwords.words('english'))
    lis=[",","."]
    stop_words.update(lis)
    word_tokens = word_tokenize(overview)
    filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
    return filtered_sentence

In [33]:
movies["overview"]=movies['overview'].apply(convert_overview)
movies["overview"]

0       [22nd, century, paraplegic, Marine, dispatched...
1       [Captain, Barbossa, long, believed, dead, come...
2       [cryptic, message, Bond, ’, past, sends, trail...
3       [Following, death, District, Attorney, Harvey,...
4       [John, Carter, war-weary, former, military, ca...
                              ...
4804    [El, Mariachi, wants, play, guitar, carry, fam...
4805    [newlywed, couple, 's, honeymoon, upended, arr...
4806    [``, Signed, Sealed, Delivered, '', introduces...
4807    [ambitious, New, York, attorney, Sam, sent, Sh...
4808    [Ever, since, second, grade, first, saw, E.T, ...
Name: overview, Length: 4806, dtype: object

In [34]:
movies["genres"].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [35]:
movies["genres"]=movies["genres"].apply(lambda x:[i.replace(" ","") for i in x])
movies["keywords"]=movies["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
movies["cast"]=movies["cast"].apply(lambda x:[i.replace(" ","") for i in x])
movies["crew"]=movies["crew"].apply(lambda x:[i.replace(" ","") for i in x])
movies.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[22nd, century, paraplegic, Marine, dispatched...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa, long, believed, dead, come...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[cryptic, message, Bond, ’, past, sends, trail...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, death, District, Attorney, Harvey,...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, war-weary, former, military, ca...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [36]:
movies["tags"]=movies["overview"]+movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]

In [37]:
movies.head()

,id,title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[22nd, century, paraplegic, Marine, dispatched...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[22nd, century, paraplegic, Marine, dispatched..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa, long, believed, dead, come...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa, long, believed, dead, come..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[cryptic, message, Bond, ’, past, sends, trail...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[cryptic, message, Bond, ’, past, sends, trail..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, death, District, Attorney, Harvey,...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, death, District, Attorney, Harvey,..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, war-weary, former, military, ca...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, war-weary, former, military, ca..."

In [38]:
new_df=movies[["id","title","tags"]]
new_df.head()

,id,title,tags
0,19995,Avatar,"[22nd, century, paraplegic, Marine, dispatched..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa, long, believed, dead, come..."
2,206647,Spectre,"[cryptic, message, Bond, ’, past, sends, trail..."
3,49026,The Dark Knight Rises,"[Following, death, District, Attorney, Harvey,..."
4,49529,John Carter,"[John, Carter, war-weary, former, military, ca..."

In [39]:
new_df["tags"]=new_df["tags"].apply(lambda x: " ".join(x))

<ipython-input-39-c4162c73f16c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x: " ".join(x))

In [40]:
new_df.head()

,id,title,tags
0,19995,Avatar,22nd century paraplegic Marine dispatched moon...
1,285,Pirates of the Caribbean: At World's End,Captain Barbossa long believed dead come back ...
2,206647,Spectre,cryptic message Bond ’ past sends trail uncove...
3,49026,The Dark Knight Rises,Following death District Attorney Harvey Dent ...
4,49529,John Carter,John Carter war-weary former military captain ...

In [41]:
new_df["tags"]=new_df["tags"].apply(lambda x:x.lower())
new_df

<ipython-input-41-e5255076b8d2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x:x.lower())

,id,title,tags
0,19995,Avatar,22nd century paraplegic marine dispatched moon...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believed dead come back ...
2,206647,Spectre,cryptic message bond ’ past sends trail uncove...
3,49026,The Dark Knight Rises,following death district attorney harvey dent ...
4,49529,John Carter,john carter war-weary former military captain ...
...,...,...,...
4804,9367,El Mariachi,el mariachi wants play guitar carry family tra...
4805,72766,Newlyweds,newlywed couple 's honeymoon upended arrivals ...
4806,231617,"Signed, Sealed, Delivered",`` signed sealed delivered '' introduces dedic...
4807,126186,Shanghai Calling,ambitious new york attorney sam sent shanghai ...
4808,25975,My Date with Drew,ever since second grade first saw e.t extrater...

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000,stop_words='english')

In [43]:
cv.fit_transform(new_df["tags"]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980s',
 '19th',
 '19thcentury',
 '20',
 '20th',
 '24',
 '30',
 '3d',
 '40',
 '50',
 'aaroneckhart',
 'abandoned',
 'abigailbreslin',
 'ability',
 'able',
 'abuse',
 'academy',
 'accepts',
 'accident',
 'accidentally',
 'account',
 'accused',
 'act',
 'action',
 'actions',
 'activities',
 'actor',
 'actors',
 'actress',
 'actually',
 'adam',
 'adamsandler',
 'adamscott',
 'adaptation',
 'addiction',
 'adopted',
 'adoption',
 'adrienbrody',
 'adult',
 'adultery',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'afghanistan',
 'africa',
 'african',
 'aftercreditsstinger',
 'afterlife',
 'age',
 'aged',
 'agency',
 'agent',
 'agents',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'air',
 'airplane',
 'airport',
 'al',
 'alanarkin',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredmolina',
 'alice',
 'alien',
 'alieninvasion',
 'aliens',
 'alike',
 'alive',
 'allen',
 'allied',
 'allies',
 'ally',
 'alpacino',
 'alter',
 'alternate',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambush',
 'america',
 'american',
 'americanfootball',
 'americans',
 'amnesia',
 'amp',
 'amyadams',
 'ancient',
 'anderson',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'anger',
 'angry',
 'animal',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annettebening',
 'annie',
 'annual',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anti',
 'antihero',
 'antoniobanderas',
 'apart',
 'apartment',
 'apocalypse',
 'apocalyptic',
 'appears',
 'apple',
 'apprentice',
 'archaeologist',
 'architect',
 'area',
 'arena',
 'armed',
 'arms',
 'army',
 'arnoldschwarzenegger',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artists',
 'arts',
 'ashtonkutcher',
 'asked',
 'asks',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'astronaut',
 'asylum',
 'athlete',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempts',
 'attention',
 'attitude',
 'attorney',
 'attractive',
 'audition',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'auto',
 'avenge',
 'avoid',
 'award',
 'away',
 'awry',
 'baby',
 'bachelor',
 'backdrop',
 'bad',
 'balance',
 'ball',
 'ballet',
 'band',
 'bank',
 'banker',
 'bar',
 'barely',
 'barry',
 'barrylevinson',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedonnovel',
 'basedonplay',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'beach',
 'bear',
 'beast',
 'beat',
 'beautiful',
 'beauty',
 'becominganadult',
 'bed',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'believe',
 'believed',
 'believes',
 'beloved',
 'ben',
 'benaffleck',
 'beniciodeltoro',
 'benkingsley',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'betrayal',
 'better',
 'bible',
 'big',
 'biggest',
 'biker',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'bizarre',
 'black',
 'blackmail',
 'blackpeople',
 'blade',
 'blind',
 'blonde',
 'blood',
 'bloody',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobby',
 'bobhoskins',
 'body',
 'bodyguard',
 'bomb',
 'bombing',
 'bond',
 'book',
 'books',
 'border',
 'bored',
 'born',
 'boss',
 'boston',
 'bound',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brave',
 'bravery',
 'break',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brian',
 'briancox',
 'bride',
 'bridge',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'buddy',
 'build',
 'building',
 'bully',
 'bumbling',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'buy',
 'ca',
 'cabin',
 'california',
 'called',
 'calls',
 'calvin',
 'came',
 'camera',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'capable',
 'capitalism',
 'captain',
 'captive',
 'capture',
 'captured',
 'car',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'caribbean',
 'carl',
 'carlagugino',
 'carmen',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'carter',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'cedrictheentertainer',
 'celebrate',
 'celebration',
 'celebrity',
 'center',
 'centered',
 'central',
 'centuries',
 'century',
 'certain',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'character',
 'characters',
 'charge',
 'charged',
 'charles',
 'charlie',
 'charlizetheron',
 'charming',
 'chase',
 'cheating',
 'chef',
 'chicago',
 'chief',
 'child',
 'childabuse',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'choice',
 'choose',
 'chosen',
 'chris',
 'chrisevans',
 'chrishemsworth',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christinaapplegate',
 'christinaricci',
 'christmas',
 'christmasparty',
 'christopherplummer',
 'christopherwalken',
 'church',
 'cia',
 'circle',
 'circumstances',
 'circus',
 'citizens',
 'city',
 'civil',
 'claim',
 'claims',
 'claire',
 'clan',
 'clash',
 'class',
 'classic',
 'classmate',
 'clean',
 'clear',
 'clerk',
 'client',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'club',
 'clues',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cold',
 'coldwar',
 'cole',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'college',
 'collide',
 'colonel',
 'coma',
 'combat',
 'come',
 'comedian',
 'comedy',
 'comes',
 'comic',
 'coming',
 'comingofage',
 'commander',
 'commitment',
 'committed',
 'common',
 'community',
 'company',
 'compete',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'computer',
 'concert',
 'condition',
 'confidence',
 'conflict',
 'confront',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'consequences',
 'conspiracy',
 'contact',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controversial',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 'count',
 'country',
 'countryside',
 'couple',
 'couples',
 'courage',
 'course',
 'court',
 'courtcase',
 'cousin',
 'cover',
 'covert',
 'cowardliness',
 'cowboy',
 'crack',
 'craig',
 'crash',
 'crazy',
 'create',
 'created',
 'creates',
 'creature',
 'creatures',
 'crew',
 'crime',
 'crimefighter',
 'crimes',
 'criminal',
 'criminals',
 'crisis',
 'crocodile',
 'cross',
 'crossed',
 'cruise',
 'crush',
 'cuba',
 'cubagoodingjr',
 'cult',
 'cultfilm',
 'cultural',
 'culture',
 'cultureclash',
 'cure',
 'current',
 'curse',
 'custody',
 'cut',
 'cyborg',
 'dad',
 'daily',
 'dan',
 'danaykroyd',
 'dance',
 'dancer',
 'dancing',
 'danger',
 'dangerous',
 'daniel',
 'danielcraig',
 'danny',
 'dannydevito',
 'dannyglover',
 'dark',
 'darkcomedy',
 'darkness',
 'date',
 'dating',
 'daughter',
 'daughters',
 'dave',
 'david',
 'davidmorse',
 'davidthewlis',
 'day',
 'days',
 'dccomics',
 'dead',
 'deadly',
 'deal',
 'dealer',
 'dealers',
 'dealing',
 'deals',
 'dean',
 'death',
 'deathofafriend',
 'debt',
 'decades',
 'deceased',
 'deceit',
 'deception',
 'decide',
 'decided',
 'decides',
 'decision',
 'decisions',
 'deep',
 'deeper',
 'deeply',
 'defeat',
 'defend',
 'defense',
 'delroylindo',
 'demands',
 'demimoore',
 'demon',
 'demons',
 'dennishopper',
 'dennisquaid',
 'denzelwashington',
 'department',
 'depressed',
 'depression',
 'deranged',
 'dermotmulroney',
 'desert',
 'desire',
 'desperate',
 'desperately',
 'despite',
 'destined',
 'destiny',
 'destroy',
 'destroyed',
 'destroying',
 'destruction',
 'detective',
 'detectives',
 'determined',
 'detroit',
 'develop',
 'develops',
 'device',
 'devil',
 'devoted',
 'diamond',
 'diane',
 'dianekeaton',
 'diary',
 'dictator',
 'die',
 'died',
 'diego',
 'dies',
 'differences',
 'different',
 'difficult',
 'diner',
 'dinner',
 'dinosaur',
 'dinosaurs',
 'directed',
 'director',
 'disappearance',
 'disappeared',
 'disappears',
 'disaster',
 'discover',
 'discovered',
 'discovering',
 'discovers',
 'discovery',
 'disease',
 'disguise',
 'disorder',
 'distant',
 'district',
 'disturbing',
 'divorce',
 'divorced',
 'dna',
 'doctor',
 'documentary',
 'dog',
 'doll',
 'dolphin',
 'donaldsutherland',
 'doncheadle',
 'donnell',
 'door',
 'double',
 'doublelife',
 'doug',
 'dr',
 'dracula',
 'dragon',
 'drama',
 'dramatic',
 'drawn',
 'draws',
 'dream',
 'dreams',
 'drewbarrymore',
 'drifter',
 'drink',
 'drinking',
 'drive',
 'driven',
 'driver',
 'drives',
 'driving',
 'drug',
 'drugaddiction',
 'drugdealer',
 'drugs',
 'drugtraffic',
 'drunk',
 'dualidentity',
 'duel',
 'duke',
 'duo',
 'duringcreditsstinger',
 'dustinhoffman',
 'duty',
 'dwaynejohnson',
 'dying',
 'dyinganddeath',
 'dysfunctionalfamily',
 'dystopia',
 'eager',
 'earlier',
 'early',
 'earth',
 'east',
 'easy',
 'eating',
 'eccentric',
 'eddie',
 'eddiemurphy',
 'edharris',
 'editor',
 'education',
 'edward',
 'edwardburns',
 'edwardnorton',
 'effort',
 'efforts',
 'egg',
 'ego',
 'egypt',
 'el',
 'elderly',
 'elijahwood',
 'elite',
 'elizabeth',
 'elizabethbanks',
 'elves',
 'embark',
 'embarks',
 'emily',
 'emilyblunt',
 'emilymortimer',
 'emma',
 'emmastone',
 'emmathompson',
 'emotions',
 'emperor',
 'empire',
 'employee',
 'employees',
 'encounter',
 'encounters',
 'end',
 'ended',
 'ending',
 'ends',
 'enemies',
 'enemy',
 'engaged',
 'engineer',
 'england',
 'english',
 'enlists',
 'ensues',
 'enter',
 'enterprise',
 'enters',
 'entire',
 'environment',
 'epic',
 'epidemic',
 'era',
 'eric',
 'eroticism',
 'escape',
 'escaped',
 'escapes',
 'especially',
 'espionage',
 'estate',
 'estranged',
 'eternal',
 'ethan',
 'ethanhawke',
 'eugenelevy',
 'europe',
 'european',
 'evamendes',
 'eve',
 'evening',
 'event',
 'events',
 'eventually',
 'everyday',
 'evidence',
 'evil',
 'ewanmcgregor',
 'ex',
 'exact',
 'exactly',
 'execution',
 'executive',
 'exist',
 'existence',
 'exorcism',
 'exotic',
 'exoticisland',
 'expected',
 'expedition',
 'experience',
 'experiences',
 'experiment',
 'expert',
 'explores',
 'explosion',
 'explosive',
 'expose',
 'extramaritalaffair',
 'extraordinary',
 'extreme',
 'extremely',
 'extremeviolence',
 'eye',
 'eyes',
 'face',
 'faced',
 'faces',
 'facility',
 'facing',
 'fact',
 'factory',
 'failed',
 'fails',
 'fairy',
 'fairytale',
 'faith',
 'fall',
 'fallen',
 'falling',
 'fallinginlove',
 'falls',
 'fame',
 'families',
 'family',
 'familyrelationships',
 'famkejanssen',
 'famous',
 'fan',
 'fangvamp',
 'fans',
 'fantasy',
 'fantasyworld',
 'far',
 'farm',
 'farmer',
 'fashion',
 'fast',
 'fat',
 'fatal',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'favorite',
 'fbi',
 'fbiagent',
 'fear',
 'fears',
 'feature',
 'featuring',
 'feel',
 'feeling',
 'feelings',
 'feels',
 'feet',
 'fellow',
 'female',
 'femalefriendship',
 'femalenudity',
 'femaleprotagonist',
 'festival',
 'fiancé',
 'fiancée',
 'fiction',
 'fictional',
 'field',
 'fierce',
 'fight',
 ...]

In [45]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [46]:
def stem(text):
    lis=[]
    for i in text.split():
        lis.append(ps.stem(i))
    return " ".join(lis)

In [47]:
new_df["tags"].apply(stem)

0       22nd centuri parapleg marin dispatch moon pand...
1       captain barbossa long believ dead come back li...
2       cryptic messag bond ’ past send trail uncov si...
3       follow death district attorney harvey dent bat...
4       john carter war-weari former militari captain ...
                              ...
4804    el mariachi want play guitar carri famili trad...
4805    newlyw coupl 's honeymoon upend arriv respect ...
4806    `` sign seal deliv '' introduc dedic quartet c...
4807    ambiti new york attorney sam sent shanghai ass...
4808    ever sinc second grade first saw e.t extraterr...
Name: tags, Length: 4806, dtype: object

In [48]:
new_df["tags"]=new_df["tags"].apply(stem)

<ipython-input-48-539595c55868>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(stem)

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000,stop_words='english')
vectors=cv.fit_transform(new_df["tags"]).toarray()
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '1930',
 '1940',
 '1950',
 '1960',
 '1970',
 '1980',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '20th',
 '24',
 '30',
 '3d',
 '40',
 '50',
 '60',
 '70',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adamsandl',
 'adamscott',
 'adapt',
 'addict',
 'admir',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adulteri',
 'advanc',
 'adventur',
 'advertis',
 'advic',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aim',
 'air',
 'airplan',
 'airport',
 'al',
 'alanarkin',
 'alaska',
 'albert',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alfredmolina',
 'alic',
 'alien',
 'alieninvas',
 'alik',
 'aliv',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alpacino',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amaz',
 'ambassador',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'americanfootbal',
 'ami',
 'amnesia',
 'amp',
 'amus',
 'amyadam',
 'analyst',
 'ancient',
 'anderson',
 'andi',
 'andrew',
 'android',
 'andygarcía',
 'angel',
 'angelabassett',
 'angelinajoli',
 'anger',
 'angri',
 'anim',
 'animalhorror',
 'ann',
 'anna',
 'annafari',
 'annehathaway',
 'annetteben',
 'anni',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anti',
 'antihero',
 'antoniobandera',
 'anyon',
 'anyth',
 'apart',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'appoint',
 'apprentic',
 'approach',
 'april',
 'arab',
 'archaeologist',
 'architect',
 'area',
 'arena',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artificialintellig',
 'artist',
 'ashleyjudd',
 'ashtonkutch',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'auto',
 'aveng',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awri',
 'babi',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'band',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barri',
 'barrylevinson',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'becam',
 'becom',
 'becominganadult',
 'bed',
 'befriend',
 'began',
 'begin',
 'behavior',
 'belief',
 'believ',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'beniciodeltoro',
 'benjaminbratt',
 'benkingsley',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'betray',
 'better',
 'bibl',
 'big',
 'biggest',
 'biker',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'biographi',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blind',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bobhoskin',
 'bodi',
 'bodyguard',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'braveri',
 'break',
 'brendanfras',
 'brendangleeson',
 'brian',
 'briancox',
 'briandepalma',
 'bride',
 'bridg',
 'brief',
 'brien',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'broadway',
 'broke',
 'broken',
 'brook',
 'brooklyn',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bu',
 'buddi',
 'build',
 'bulli',
 'bumbl',
 'buri',
 'burn',
 'bush',
 'busi',
 'businessman',
 'bust',
 'buy',
 'ca',
 'cabin',
 'cal',
 'california',
 'calvin',
 'came',
 'camera',
 'camerondiaz',
 'camp',
 'campaign',
 'campbel',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'cannib',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'caribbean',
 'carl',
 'carlagugino',
 'carmen',
 'carrac',
 'carri',
 'carter',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'caught',
 'caus',
 'cave',
 'cedrictheentertain',
 'celebr',
 'center',
 'central',
 'centuri',
 'certain',
 'chain',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chang',
 'channingtatum',
 'chao',
 'charact',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlizetheron',
 'charm',
 'chase',
 'chazzpalminteri',
 'cheat',
 'cheerlead',
 'chef',
 'chemic',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhood',
 'children',
 'china',
 'chines',
 'chip',
 'chloëgracemoretz',
 'choic',
 'choos',
 'chosen',
 'chri',
 'chrisevan',
 'chrishemsworth',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmasparti',
 'christoph',
 'christopherplumm',
 'christopherwalken',
 'chronicl',
 'church',
 'cia',
 'circl',
 'circu',
 'circumst',
 'citi',
 'citizen',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'clean',
 'clear',
 'clerk',
 'client',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'club',
 'clue',
 'coach',
 'coast',
 'cocain',
 'code',
 'cold',
 'coldwar',
 'cole',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'collid',
 'colonel',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comedi',
 'comedian',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'command',
 'commerci',
 'commit',
 'common',
 'commun',
 'compani',
 'companion',
 'compet',
 'competit',
 'complet',
 'complex',
 'complic',
 'compos',
 'comput',
 'concern',
 'concert',
 'condit',
 'confid',
 'conflict',
 'confront',
 'confus',
 'congress',
 'connect',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consid',
 'conspiraci',
 'construct',
 'consum',
 'contact',
 'contain',
 'contend',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'corner',
 'corpor',
 'corps',
 'corrupt',
 'cost',
 'costum',
 'count',
 'countri',
 'countrysid',
 'coupl',
 'courag',
 'cours',
 'court',
 'courtcas',
 'cousin',
 'cover',
 'covert',
 'cowardli',
 'cowboy',
 'crack',
 'craig',
 'crash',
 'crazi',
 'creat',
 'creator',
 'creatur',
 'crew',
 'crime',
 'crimefight',
 'crimin',
 'crisi',
 'critic',
 'crocodil',
 'crook',
 'cross',
 'cruel',
 'cruelti',
 'cruis',
 'crusad',
 'crush',
 'cuba',
 'cubagoodingjr',
 'cult',
 'cultfilm',
 'cultur',
 'cultureclash',
 'cure',
 'current',
 'curs',
 'custodi',
 'custom',
 'cut',
 'cyborg',
 'cynic',
 'dad',
 'daili',
 'damag',
 'dan',
 'danaykroyd',
 'danc',
 'dancer',
 'danger',
 'daniel',
 'danielcraig',
 'danni',
 'dannydevito',
 'dannyglov',
 'dare',
 'dark',
 'darkcomedi',
 'darylhannah',
 'date',
 'daughter',
 'dave',
 'davi',
 'david',
 'davidmors',
 'davidthewli',
 'day',
 'dccomic',
 'dead',
 'deadli',
 'deal',
 'dealer',
 'dean',
 'death',
 'deathofafriend',
 'debt',
 'decad',
 'deceas',
 'deceit',
 'decept',
 'decid',
 'decis',
 'declar',
 'dedic',
 'deed',
 'deep',
 'deeper',
 'deepli',
 'defeat',
 'defend',
 'defens',
 'deliv',
 'delroylindo',
 'delus',
 'demand',
 'demimoor',
 'demon',
 'dennishopp',
 'dennisquaid',
 'dentist',
 'denzelwashington',
 'depart',
 'depict',
 'depress',
 'derang',
 'dermotmulroney',
 'descend',
 'desert',
 'design',
 'desir',
 'desper',
 'despit',
 'destin',
 'destini',
 'destroy',
 'destruct',
 'detect',
 'determin',
 'detroit',
 'devast',
 'develop',
 'devic',
 'devil',
 'devot',
 'diamond',
 'dian',
 'dianekeaton',
 'dianelan',
 'diari',
 'dictat',
 'die',
 'diego',
 'differ',
 'difficult',
 'dig',
 'diner',
 'dinner',
 'dinosaur',
 'direct',
 'director',
 'dirtycop',
 'disabl',
 'disappear',
 'disast',
 'discov',
 'discoveri',
 'diseas',
 'disfigur',
 'disguis',
 'disord',
 'dispatch',
 'distant',
 'district',
 'disturb',
 'divorc',
 'dna',
 'doctor',
 'document',
 'documentari',
 'dog',
 'doll',
 'dollar',
 'dolphin',
 'domin',
 'donaldsutherland',
 'doncheadl',
 'donnel',
 'doom',
 'door',
 'doubl',
 'doublelif',
 'doubt',
 'doug',
 'dr',
 'dracula',
 'drag',
 'dragon',
 'drama',
 'dramat',
 'draw',
 'drawn',
 'dream',
 'dress',
 'drewbarrymor',
 'drifter',
 'drink',
 'drive',
 'driven',
 'driver',
 'drop',
 'drug',
 'drugaddict',
 'drugdeal',
 'drugtraff',
 'drunk',
 'dualident',
 'duel',
 'duke',
 'dump',
 'duo',
 'duringcreditssting',
 'dustinhoffman',
 'duti',
 'dwaynejohnson',
 'dyinganddeath',
 'dynam',
 'dysfunctionalfamili',
 'dystopia',
 'dystopicfutur',
 'eager',
 'earli',
 'earlier',
 'earn',
 'earth',
 'easi',
 'east',
 'eat',
 'eccentr',
 'econom',
 'eddi',
 'eddiemurphi',
 'edg',
 'edharri',
 'editor',
 'educ',
 'edward',
 'edwardburn',
 'edwardnorton',
 'effect',
 'effort',
 'egg',
 'ego',
 'egypt',
 'el',
 'elderli',
 'elect',
 'element',
 'elijahwood',
 'elimin',
 'elit',
 'elizabeth',
 'elizabethbank',
 'elli',
 'els',
 'elud',
 'elv',
 'embark',
 'emerg',
 'emili',
 'emilyblunt',
 'emilymortim',
 'emilywatson',
 'emma',
 'emmaston',
 'emmathompson',
 'emot',
 'emperor',
 'empir',
 'employ',
 'employe',
 'encount',
 'end',
 'enemi',
 'energi',
 'enforc',
 'engag',
 'engin',
 'england',
 'english',
 'enjoy',
 'enlist',
 'ensu',
 'entangl',
 'enter',
 'enterpris',
 'entertain',
 'entir',
 'environ',
 'epic',
 'epidem',
 'equal',
 'era',
 'eric',
 'ericbana',
 'erotic',
 'erupt',
 'escap',
 'especi',
 'espionag',
 'establish',
 'estat',
 'estrang',
 'etern',
 'ethan',
 'ethanhawk',
 'eugenelevi',
 'europ',
 'european',
 'evamend',
 'eve',
 'event',
 'eventu',
 'everi',
 'everyday',
 'everyon',
 'everyth',
 'evid',
 'evil',
 'evolv',
 'ewanmcgregor',
 'ex',
 'exact',
 'exactli',
 'examin',
 'exchang',
 'excit',
 'execut',
 'exist',
 'exorc',
 'exot',
 'exoticisland',
 'expect',
 'expedit',
 'experi',
 'experienc',
 'expert',
 'explod',
 'exploit',
 'explor',
 'explos',
 'expos',
 'extramaritalaffair',
 'extraordinari',
 'extrem',
 'extremeviol',
 'eye',
 'fac',
 'face',
 'facil',
 'fact',
 'factori',
 'fade',
 'fail',
 'fairi',
 'fairytal',
 'faith',
 'fake',
 'fall',
 'fallen',
 'fallinginlov',
 'fame',
 'famili',
 'family',
 'familyrelationship',
 'famkejanssen',
 'famou',
 'fan',
 'fangvamp',
 'fantasi',
 'fantast',
 'fantasyworld',
 'far',
 'farm',
 'farmer',
 'fascin',
 'fashion',
 'fast',
 ...]

In [51]:
vectors.shape

(4806, 3000)

In [52]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.08980265, 0.08980265, ..., 0.06933752, 0.02635231,
        0.        ],
       [0.08980265, 1.        , 0.06451613, ..., 0.02490677, 0.        ,
        0.        ],
       [0.08980265, 0.06451613, 1.        , ..., 0.04981355, 0.        ,
        0.        ],
       ...,
       [0.06933752, 0.02490677, 0.04981355, ..., 1.        , 0.06577935,
        0.04756515],
       [0.02635231, 0.        , 0.        , ..., 0.06577935, 1.        ,
        0.05423261],
       [0.        , 0.        , 0.        , ..., 0.04756515, 0.05423261,
        1.        ]])

In [53]:
similarity.shape

(4806, 4806)

In [54]:
new_df["title"]=="Avatar"

0        True
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Name: title, Length: 4806, dtype: bool

In [55]:
new_df[new_df["title"]=="Avatar"]

      id   title                                               tags
0  19995  Avatar  22nd centuri parapleg marin dispatch moon pand...

In [56]:
new_df[new_df["title"]=="Avatar"].index

Int64Index([0], dtype='int64')

In [57]:
new_df[new_df["title"]=="Avatar"].index[0]

0

In [58]:
new_df[new_df["title"]=="Titanic"].index[0]

25

In [59]:
sorted(similarity[0],reverse=True)[:10]

[1.0,
 0.323575114464717,
 0.2830692585361489,
 0.2773500981126145,
 0.2676516895156554,
 0.26190476190476186,
 0.2608745973749754,
 0.25724787771376323,
 0.25717224993681986,
 0.2465984809580359]

In [60]:
list(enumerate(similarity[0]))[:10]

[(0, 1.0),
 (1, 0.08980265101338746),
 (2, 0.08980265101338746),
 (3, 0.07856742013183862),
 (4, 0.20823168251814142),
 (5, 0.11446713662390752),
 (6, 0.03984095364447979),
 (7, 0.16839382851364085),
 (8, 0.06804138174397717),
 (9, 0.09622504486493763)]

In [61]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[:10]

[(0, 1.0),
 (3730, 0.323575114464717),
 (1216, 0.2830692585361489),
 (507, 0.2773500981126145),
 (61, 0.2676516895156554),
 (582, 0.26190476190476186),
 (151, 0.2608745973749754),
 (539, 0.25724787771376323),
 (2409, 0.25717224993681986),
 (1920, 0.2465984809580359)]

In [83]:
def recommend(movie):
    movie_index=new_df[new_df["title"]==movie].index[0]
    distances=sorted(list(enumerate(similarity[movie_index])),reverse=True,key=lambda x:x[1])
    for movie in distances[1:6]:
        print(new_df.iloc[movie[0]].title)

In [ ]:
recommend('Batman Begins')

In [78]:
import pickle

In [81]:
pickle.dump(new_df.to_dict(),open("movies.pkl","wb"))

In [82]:
pickle.dump(similarity,open("similarity.pkl","wb"))